
# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14

# The URL the site will be built for
base_url = "https://giou-k.github.io"
title = "SoftwareEngineering.Flush"
description = "Curated posts, braindumps and projects on Go, System Design and Blockchain, by Giou."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
theme = "dark"
toc = true
favicon = "/icons/favicon.jpeg"
fancy_code = true
dynamic_note = true

socials = [
    { name = "github", url = "https://github.com/giou-k", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/konstantinos-georgiou-giou/", icon = "linkedin" },
]

menu = [
    { name = "/curated", url = "/curated", weight = 1 },
    { name = "/flush", url = "/flush", weight = 2 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]
